name: Linters

on:
  push:
    branches:
      - main
      - v2.**
  pull_request:

jobs:

  php-cs-fixer:
    name: linter
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP with Composer and extensions
        with:
          php-version: 8.1
          tools: php-cs-fixer
        uses: shivammathur/setup-php@v2

      - name: Run php-cs-fixer
        run: php-cs-fixer fix --diff --dry-run --allow-risky=yes --using-cache=no
